PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/DSL/HR80_VVERGI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /DSL/HR80_VVERGI-GRTAX .
    FIELD /DSL/HR80_VVERGI-SSKOD .
    FIELD /DSL/HR80_VVERGI-SSGRP .
    FIELD /DSL/HR80_VVERGI-ENDDA .
    FIELD /DSL/HR80_VVERGI-BEGDA .
    FIELD /DSL/HR80_VVERGI-OEZEL .
    FIELD /DSL/HR80_VVERGI-COCUK .
    FIELD /DSL/HR80_VVERGI-IMBTR .
    FIELD /DSL/HR80_VVERGI-AILE .
    FIELD /DSL/HR80_VVERGI-WAERS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /DSL/HR80_VVERGI-GRTAX .
    FIELD /DSL/HR80_VVERGI-SSKOD .
    FIELD /DSL/HR80_VVERGI-SSGRP .
    FIELD /DSL/HR80_VVERGI-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
