@AbapCatalog.sqlViewName: '/DSL/HR80_DDL005'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Bütçe - Personel yıllık bordro sonuçları (SON)'
@Metadata.ignorePropagatedAnnotations: true
define view /DSL/HR80_CDS005
  as select from /dsl/hr80_ddl004 as payroll
{

  key  payroll.molga,
  key  gjahr,
  key  payroll.grpid,
  key  payroll.vrsid,
  key  rfper,
  key  pernr,
  key  ztabl,
  key  payroll.lgart,
       //
       ename,
       lgtxt,
       momag,
       payroll.ktopl,
       //
       sum( payroll.betrg01  ) as bet01,
       sum( payroll.betrg02  ) as bet02,
       sum( payroll.betrg03  ) as bet03,
       sum( payroll.betrg04  ) as bet04,
       sum( payroll.betrg05  ) as bet05,
       sum( payroll.betrg06  ) as bet06,
       sum( payroll.betrg07  ) as bet07,
       sum( payroll.betrg08  ) as bet08,
       sum( payroll.betrg09  ) as bet09,
       sum( payroll.betrg10  ) as bet10,
       sum( payroll.betrg11  ) as bet11,
       sum( payroll.betrg12  ) as bet12,
       //
       pa1_begda,
       pa1_endda,
       payroll.bukrs,
       bukrs_t,
       orgeh,
       orgeh_t,
       plans,
       plans_t,
       stell,
       stell_t,
       kokrs,
       kokrs_t,
       kostl,
       kostl_t,
       werks,
       werks_t,
       werks_new,
       btrtl,
       btrtl_t,
       btrtl_new,
       persg,
       ptext_t,
       persg_new,
       persg_new_t,
       persk,
       persk_t,
       persk_new,
       persk_new_t,
       ssgrp,
       kanun,
       prozt,
       trfar,
       trfar_t,
       trfar_new,
       trfar_new_t,
       trfgb,
       trfgb_t,
       trfgb_new,
       trfgb_new_t,
       trfgr,
       trfgr_new,
       trfst,
       trfst_new,
       lga01,
       salry,
       lga01_new,
       salry_new,
       mgart,
       massn,
       massn_t,
       massg,
       massg_t,
       stat2,
       ansvh,
       abkrs,
       waers,

       //
       sum( payroll.anzhl01  ) as anz01,
       sum( payroll.anzhl02  ) as anz02,
       sum( payroll.anzhl03  ) as anz03,
       sum( payroll.anzhl04  ) as anz04,
       sum( payroll.anzhl05  ) as anz05,
       sum( payroll.anzhl06  ) as anz06,
       sum( payroll.anzhl07  ) as anz07,
       sum( payroll.anzhl08  ) as anz08,
       sum( payroll.anzhl09  ) as anz09,
       sum( payroll.anzhl10  ) as anz10,
       sum( payroll.anzhl11  ) as anz11,
       sum( payroll.anzhl12  ) as anz12,
       //
       sum( payroll.betpe01  ) as btp01,
       sum( payroll.betpe02  ) as btp02,
       sum( payroll.betpe03  ) as btp03,
       sum( payroll.betpe04  ) as btp04,
       sum( payroll.betpe05  ) as btp05,
       sum( payroll.betpe06  ) as btp06,
       sum( payroll.betpe07  ) as btp07,
       sum( payroll.betpe08  ) as btp08,
       sum( payroll.betpe09  ) as btp09,
       sum( payroll.betpe10  ) as btp10,
       sum( payroll.betpe11  ) as btp11,
       sum( payroll.betpe12  ) as btp12
       //
}
group by
  payroll.molga,
  gjahr,
  payroll.grpid,
  payroll.vrsid,
  rfper,
  pernr,
  ztabl,
  payroll.lgart,

  ename,
  lgtxt,
  momag,
  payroll.ktopl,

  //
  //
  pa1_begda,
  pa1_endda,
  payroll.bukrs,
  bukrs_t,
  orgeh,
  orgeh_t,
  plans,
  plans_t,
  stell,
  stell_t,
  kokrs,
  kokrs_t,
  kostl,
  kostl_t,
  werks,
  werks_t,
  werks_new,
  btrtl,
  btrtl_t,
  btrtl_new,
  persg,
  ptext_t,
  persg_new,
  persg_new_t,
  persk,
  persk_t,
  persk_new,
  persk_new_t,
  ssgrp,
  kanun,
  prozt,
  trfar,
  trfar_t,
  trfar_new,
  trfar_new_t,
  trfgb,
  trfgb_t,
  trfgb_new,
  trfgb_new_t,
  trfgr,
  trfgr_new,
  trfst,
  trfst_new,
  lga01,
  salry,
  lga01_new,
  salry_new,
  mgart,
  massn,
  massn_t,
  massg,
  massg_t,
  stat2,
  ansvh,
  abkrs,
  waers




//
