PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/DSL/HR80_VVERGD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /DSL/HR80_VVERGD-GRTAX .
    FIELD /DSL/HR80_VVERGD-DILIM .
    FIELD /DSL/HR80_VVERGD-ENDDA .
    FIELD /DSL/HR80_VVERGD-BEGDA .
    FIELD /DSL/HR80_VVERGD-ANBTR .
    FIELD /DSL/HR80_VVERGD-ENBTR .
    FIELD /DSL/HR80_VVERGD-WAERS .
    FIELD /DSL/HR80_VVERGD-PRZNT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /DSL/HR80_VVERGD-GRTAX .
    FIELD /DSL/HR80_VVERGD-DILIM .
    FIELD /DSL/HR80_VVERGD-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
