PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/DSL/HR80_V002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /DSL/HR80_V002-BUKRS .
    FIELD /DSL/HR80_V002-BUTXT .
    FIELD /DSL/HR80_V002-WERKS .
    FIELD /DSL/HR80_V002-NAME1 .
    FIELD /DSL/HR80_V002-BTRTL .
    FIELD /DSL/HR80_V002-BTEXT .
    FIELD /DSL/HR80_V002-ABKRS .
    FIELD /DSL/HR80_V002-ATEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/DSL/HR80_V002 ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /DSL/HR80_V002-BUKRS .
    FIELD /DSL/HR80_V002-WERKS .
    FIELD /DSL/HR80_V002-BTRTL .
    FIELD /DSL/HR80_V002-ABKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
