PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/DSL/HR80_V005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /DSL/HR80_V005-PERNR .
    FIELD /DSL/HR80_V005-LGART .
    FIELD /DSL/HR80_V005-BEGDA .
    FIELD /DSL/HR80_V005-ENDDA .
    FIELD /DSL/HR80_V005-ANZHL .
    FIELD /DSL/HR80_V005-BETRG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /DSL/HR80_V005-PERNR .
    FIELD /DSL/HR80_V005-LGART .
    FIELD /DSL/HR80_V005-BEGDA .
    FIELD /DSL/HR80_V005-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
