PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/DSL/HR80_V013 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /DSL/HR80_V013-BUKRS .
    FIELD /DSL/HR80_V013-LGART .
    FIELD /DSL/HR80_V013-SEQNO .
    FIELD /DSL/HR80_V013-ENDDA .
    FIELD /DSL/HR80_V013-SIGN .
    FIELD /DSL/HR80_V013-SYMKO .
    FIELD /DSL/HR80_V013-SPPRC .
    FIELD /DSL/HR80_V013-C1IGN .
    FIELD /DSL/HR80_V013-AUART .
    FIELD /DSL/HR80_V013-LGTXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/DSL/HR80_V013 ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /DSL/HR80_V013-BUKRS .
    FIELD /DSL/HR80_V013-LGART .
    FIELD /DSL/HR80_V013-SEQNO .
    FIELD /DSL/HR80_V013-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
